name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev/**' 

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/wrapper-validation-action@v2
      # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
          prefix: "build/${{ github.ref }}"
      - run: git config --global user.email "nobody@example.com"
      - run: git config --global user.name "Nobody"
      - run: ./gradlew applyPatches
      - run: ./gradlew build publish -x check -x test --stacktrace
        working-directory: patched-quilt-loom
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
